#!/usr/bin/env python3
import requests, json, sys

url = "http://localhost:3000/weight"
headers = {'Accept' : "application/json"}

if __name__ == '__main__':
    if len(sys.argv) == 1:
        r = requests.get(url, headers=headers)
        for weight in r.json():
            print("- %s: %.2f kg" % (weight['date'], weight['weight']))
    elif len(sys.argv) == 2:
        # put weight
        new_weight = json.dumps({'weight' : float(sys.argv[1])})
        r = requests.post(url, data=new_weight,
                          headers={'Content-Type' : 'application/json'})
        print(new_weight)
        print(r)
        print(r.content)
    else:
        print("Invalid argument. Usage weight <input weight>")
